#!/bin/bash

echo "========================================"
echo " CLIENTE – SISTEMA MÉDICO"
echo "========================================"
echo ""

echo "COMO RODAR O CLIENT:"
echo ""
echo "Opção 1) Usando docker-compose (ambiente completo):"
echo "  docker-compose up -d --build"
echo "  docker-compose exec client bash"
echo ""
echo "Opção 2) Rodando apenas o client (imagem pronta):"
echo "  docker run --rm -it \\"
echo "    -e API_HOST=host.docker.internal \\"
echo "    -e API_PORT=8080 \\"
echo "    lucasmt1/client-sistema-medico:latest"
echo ""

echo "USUÁRIOS (CRUD controlado por ROLE):"
echo "  python user.py criar <NOME> <SENHA> <ROLE>"
echo "  python user.py visualizar <ROLE> <ID>"
echo "  python user.py atualizar <ROLE> <ID> campo=valor [campo=valor ...]"
echo "  python user.py deletar <ROLE> <ID>"
echo ""

echo "ROLES ACEITAS:"
echo "  Paciente | Medico | Recepcionista | Admin"
echo ""

echo "REGRAS IMPORTANTES:"
echo "  - Usuários comuns só podem visualizar, atualizar ou deletar o próprio perfil."
echo "  - Admin pode visualizar, atualizar e deletar qualquer usuário."
echo "  - Campos não permitidos para a role são bloqueados no client."
echo ""

echo "AUTENTICAÇÃO:"
echo "  python auth.py login <CPF> <SENHA>"
echo "  cat /home/client/.token.txt    # Mostrar token atual"
echo "  rm /home/client/.token.txt     # Logout"
echo ""

echo "AGENDAMENTOS (CRUD):"
echo "  python scheduling.py criar <PACIENTE_ID> <MEDICO_ID> <ESPECIALIDADE> <DATA_ISO>"
echo "  python scheduling.py paciente <PACIENTE_ID> # Listar agendamentos do paciente"
echo "  python scheduling.py status <AGENDAMENTO_ID> <STATUS> # Atualizar status"
echo "  python scheduling.py cancelar 1 <AGENDAMENTO_ID> # Cancelar agendamento"
echo "  Exemplo:"
echo "  python scheduling.py criar 1 1 Cardiologia 2026-01-10T14:00:00"
echo ""

echo "VALIDAÇÕES / PAGAMENTOS:"
echo "  Validar convênio (Health Insurance):"
echo "  python validate.py health-insurance <PACIENTE_ID> <MEDICO_ID> <CONVENIO> <DESCRICAO>"
echo "  OBSERVAÇÃO: Apenas Admin, Médico ou Recepcionista podem autorizar convênios."

echo ""
echo "  Validar pagamento privado:"
echo "  python validate.py private-payment <PACIENTE_ID> <MEDICO_ID> <VALOR> <METODO>"
echo "  Exemplo:"
echo "  python validate.py private-payment 1 1 250 PIX"
echo "  OBSERVAÇÃO: Apenas Paciente pode autorizar pagamento privado."
echo ""

echo "CONSUMER (RabbitMQ):"
echo "  python consumer.py"
echo "  (Escuta notificações e salva em /app/data/notifications.log)"
echo ""

echo "EXEMPLO DE FLUXO COMPLETO:"
echo ""
echo "1) Criar um paciente:"
echo "   python user.py criar Joao senha123 Paciente"
echo ""
echo ""
echo "2) Criar um medico:"
echo "   python user.py criar Vitor senha123 Medico"
echo ""
echo "3) Fazer login (use o CPF gerado):"
echo "   python auth.py login <CPF> senha123"
echo ""
echo "4) Criar um agendamento:"
echo "   python scheduling.py criar <PACIENTE_ID> <MEDICO_ID> Cardiologia 2026-01-10T14:00:00"
echo ""
echo "5) Autorizar pagamento (escolha uma opção):"
echo "   a) Convênio:"
echo "      python validate.py health-insurance <PACIENTE_ID> <MEDICO_ID> Unimed Consulta"
echo ""
echo "   b) Pagamento privado:"
echo "      python validate.py private-payment <PACIENTE_ID> <MEDICO_ID> 250 PIX"
echo ""
echo "6) Visualizar o próprio perfil:"
echo "   python user.py visualizar Paciente <ID>"
echo ""
echo "7) Atualizar dados permitidos:"
echo "   python user.py atualizar Paciente <ID> Nome=JoaoSilva Telefone=11999999999"
echo ""
echo "8) Deletar o próprio perfil:"
echo "   python user.py deletar Paciente <ID>"
echo ""

echo "========================================"
echo " FIM DO HELP"
echo "========================================"
