#!/bin/bash

echo "========================================"
echo " CLIENTE SISTEMA MÉDICO"
echo "========================================"
echo ""
echo "USUÁRIOS (CRUD por ROLE):"
echo "  python user.py criar <NOME> <SENHA> <ROLE>"
echo "  python user.py visualizar <ROLE> <ID>"
echo "  python user.py atualizar <ROLE> <ID> campo=valor [campo=valor ...]"
echo "  python user.py deletar <ROLE> <ID>"
echo ""
echo "Roles aceitas: Paciente | Medico | Recepcionista | Admin"
echo ""
echo "⚠️ Observações:"
echo "  - Usuários só podem atualizar ou deletar o próprio perfil."
echo "  - Admin pode atualizar ou visualizar qualquer usuário."
echo "  - Campos não permitidos para a role serão bloqueados no client."
echo ""
echo "AUTENTICAÇÃO:"
echo "  python auth.py login <CPF> <SENHA>"
echo "  cat /home/client/.token.txt        - Mostrar token atual"
echo "  rm /home/client/.token.txt         - Logout"
echo ""
echo "AGENDAMENTOS:"
echo "  python scheduling.py criar 1 1 "Cardiologia" "2026-01-10T14:00:00""
echo ""
echo "CONSUMER (RabbitMQ):"
echo "  python consumer.py"
echo "  (Escuta notificações e salva em /app/data/notifications.log)"
echo ""
echo "EXEMPLO DE FLUXO:"
echo "1) Criar um paciente:"
echo "   python user.py criar Joao senha123 Paciente"
echo "2) Fazer login (use o CPF gerado):"
echo "   python auth.py login <CPF> senha123"
echo "3) Visualizar próprio perfil:"
echo "   python user.py visualizar Paciente <ID>"
echo "4) Atualizar dados permitidos:"
echo "   python user.py atualizar Paciente <ID> Nome=JoaoSilva Telefone=11999999999"
echo "5) Deletar próprio perfil:"
echo "   python user.py deletar Paciente <ID>"
echo " FIM DO HELP"
echo "========================================"