echo "========================================"
echo "CLIENTE SISTEMA MÉDICO"
echo "========================================"
echo ""
echo "Scripts disponíveis:"
echo "python users.py criar <nome> <senha> <tipo>"
echo "python agendamento.py <comando>"
echo "python consumer.py"
echo ""
echo "Para testar conexão com o backend:"
echo "1. Certifique-se que o backend está rodando"
echo "2. Execute: python users.py listar"
echo ""
echo "Configurações atuais:"
echo "API: ${API_HOST:-host.docker.internal}:${API_PORT:-8080}"
echo "RabbitMQ: ${RABBITMQ_HOST:-host.docker.internal}:5672"
echo "=== COMANDOS DE AUTENTICAÇÃO ==="
echo "python auth.py login <CPF> <SENHA>    - Faz login e salva token"
echo "python scheduling.py criar <JSON>    - Cria agendamento (requer token)"
echo "cat /home/client/.token.txt           - Mostra token atual"
echo "rm /home/client/.token.txt            - Remove token (logout)"
echo "========================================"